### ISSUE TITLE
undefined method `table_name=` for Delayed::Backend::ActiveRecord::Job:Class

### ISSUE THREAD

**Issue by ewamarciniak** [collectiveidea/delayed_job_active_record#187]
I am using Rails 5.2. and when upgrading to the latest version of your gem `4.1.5` I get the following error:

```
NoMethodError: undefined method `table_name=' for Delayed::Backend::ActiveRecord::Job:Class
/home/runner/_work/voice/voice/config/initializers/delayed_job.rb:18:in `<class:Job>'
```

delayed_job.rb lines 17-18:

```
class Delayed::Backend::ActiveRecord::Job
  self.table_name = 'foo_delayed_jobs'
  ...
end
```

I cannot pinpoint the exact code change that is responsible for this but this was not an issue in version `4.1.4`. Can you please let me know if this is a bug or is there any additional change required on our side after this patch upgrade?

**Comment by albus522** [comment]
That is not the correct class definition. You are defining an empty ruby class that does not inherit from ActiveRecord. This probably accidentally worked because Delayed Job would have been fully initialized at this point. However, due to some obscure ActiveRecord autoloading issues, we needed to delay initializing until the tail end of the app initialization process. See  #185 for how to wrap the code. In addition to that change, you will want to avoid redefining the job class, `table_name=` is not a private method. `Delayed::Backend::ActiveRecord::Job.table_name = 'foo_delayed_jobs'`
